# Cloud Build configuration for deploying both frontend and backend to Cloud Run
steps:
  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/conekt-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/conekt-backend:latest'
      - './backend'
    id: 'build-backend'

  # Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/conekt-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/conekt-frontend:latest'
      - './frontend'
    id: 'build-frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/conekt-backend:$COMMIT_SHA'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/conekt-frontend:$COMMIT_SHA'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'conekt-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/conekt-backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},GEMINI_API_KEY=${_GEMINI_API_KEY},SECRET_KEY=${_SECRET_KEY},ALGORITHM=HS256,ACCESS_TOKEN_EXPIRE_MINUTES=30'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'conekt-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/conekt-frontend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/conekt-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/conekt-backend:latest'
  - 'gcr.io/$PROJECT_ID/conekt-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/conekt-frontend:latest'

# Substitution variables (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _DATABASE_URL: 'postgresql://user:pass@host/db'  # Override this
  _GEMINI_API_KEY: 'your-key-here'  # Override this
  _SECRET_KEY: 'your-secret-key-here'  # Override this

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

