"""Initial optimized schema with foreign keys and indexes

Revision ID: 242b6d41c77c
Revises: 
Create Date: 2026-02-05 15:40:43.606409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '242b6d41c77c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('candidates', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'work_history',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('candidates', 'skills',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('candidates', 'certifications',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('candidates', 'education',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('candidates', 'candidate_vector',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_experience_active', 'candidates', ['experience_years', 'is_active'], unique=False)
    op.create_index(op.f('ix_candidates_experience_years'), 'candidates', ['experience_years'], unique=False)
    op.create_index(op.f('ix_candidates_is_active'), 'candidates', ['is_active'], unique=False)
    op.create_index(op.f('ix_candidates_title'), 'candidates', ['title'], unique=False)
    op.add_column('chat_messages', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.alter_column('chat_messages', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_messages', 'from_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_messages', 'to_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_chat_messages_from_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_project_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_to_user_id'), table_name='chat_messages')
    op.create_index('idx_conversation', 'chat_messages', ['project_id', 'from_user_id', 'to_user_id'], unique=False)
    op.create_index('idx_unread_messages', 'chat_messages', ['to_user_id', 'is_read'], unique=False)
    op.create_index('idx_user_messages', 'chat_messages', ['to_user_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'users', ['from_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_messages', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_messages', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('match_count', sa.Integer(), nullable=True))
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'languages',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('projects', 'frameworks',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('projects', 'domains',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('projects', 'skills',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('projects', 'roles',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'project_vector',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_active_owner', 'projects', ['is_active', 'owner_id'], unique=False)
    op.create_index('idx_created_active', 'projects', ['created_at', 'is_active'], unique=False)
    op.create_index(op.f('ix_projects_complexity'), 'projects', ['complexity'], unique=False)
    op.create_index(op.f('ix_projects_is_active'), 'projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('skill_gap_analyses', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skill_gap_analyses', 'required_skills',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('skill_gap_analyses', 'current_skills',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('skill_gap_analyses', 'skill_gaps',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('skill_gap_analyses', 'strengths',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('skill_gap_analyses', 'learning_roadmap',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('skill_gap_analyses', 'recommended_courses',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_skill_gap_analyses_analyzed_by_user_id'), table_name='skill_gap_analyses')
    op.drop_index(op.f('ix_skill_gap_analyses_candidate_id'), table_name='skill_gap_analyses')
    op.create_index('idx_candidate_score', 'skill_gap_analyses', ['candidate_id', 'readiness_score'], unique=False)
    op.create_index('idx_role_score', 'skill_gap_analyses', ['target_role', 'readiness_score'], unique=False)
    op.create_index(op.f('ix_skill_gap_analyses_readiness_score'), 'skill_gap_analyses', ['readiness_score'], unique=False)
    op.create_index(op.f('ix_skill_gap_analyses_target_role'), 'skill_gap_analyses', ['target_role'], unique=False)
    op.create_foreign_key(None, 'skill_gap_analyses', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'skill_gap_analyses', 'users', ['analyzed_by_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('swipes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('swipes', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('swipes', 'is_like',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_swipes_project_id'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_user_id'), table_name='swipes')
    op.create_index('idx_project_like', 'swipes', ['project_id', 'is_like'], unique=False)
    op.create_index('idx_user_like_created', 'swipes', ['user_id', 'is_like', 'created_at'], unique=False)
    op.create_index('idx_user_project_swipe', 'swipes', ['user_id', 'project_id'], unique=False)
    op.create_unique_constraint('uq_user_project_swipe', 'swipes', ['user_id', 'project_id'])
    op.create_foreign_key(None, 'swipes', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'swipes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'skills',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'github_selected_repos',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'top_languages',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'top_frameworks',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'user_vector',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_active_created', 'users', ['is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index('idx_active_created', table_name='users')
    op.alter_column('users', 'user_vector',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'top_frameworks',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'top_languages',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'github_selected_repos',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'skills',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'swipes', type_='foreignkey')
    op.drop_constraint(None, 'swipes', type_='foreignkey')
    op.drop_constraint('uq_user_project_swipe', 'swipes', type_='unique')
    op.drop_index('idx_user_project_swipe', table_name='swipes')
    op.drop_index('idx_user_like_created', table_name='swipes')
    op.drop_index('idx_project_like', table_name='swipes')
    op.create_index(op.f('ix_swipes_user_id'), 'swipes', ['user_id'], unique=False)
    op.create_index(op.f('ix_swipes_project_id'), 'swipes', ['project_id'], unique=False)
    op.alter_column('swipes', 'is_like',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('swipes', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('swipes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'skill_gap_analyses', type_='foreignkey')
    op.drop_constraint(None, 'skill_gap_analyses', type_='foreignkey')
    op.drop_index(op.f('ix_skill_gap_analyses_target_role'), table_name='skill_gap_analyses')
    op.drop_index(op.f('ix_skill_gap_analyses_readiness_score'), table_name='skill_gap_analyses')
    op.drop_index('idx_role_score', table_name='skill_gap_analyses')
    op.drop_index('idx_candidate_score', table_name='skill_gap_analyses')
    op.create_index(op.f('ix_skill_gap_analyses_candidate_id'), 'skill_gap_analyses', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_skill_gap_analyses_analyzed_by_user_id'), 'skill_gap_analyses', ['analyzed_by_user_id'], unique=False)
    op.alter_column('skill_gap_analyses', 'recommended_courses',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('skill_gap_analyses', 'learning_roadmap',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('skill_gap_analyses', 'strengths',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('skill_gap_analyses', 'skill_gaps',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('skill_gap_analyses', 'current_skills',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('skill_gap_analyses', 'required_skills',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('skill_gap_analyses', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_active'), table_name='projects')
    op.drop_index(op.f('ix_projects_complexity'), table_name='projects')
    op.drop_index('idx_created_active', table_name='projects')
    op.drop_index('idx_active_owner', table_name='projects')
    op.alter_column('projects', 'project_vector',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'roles',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'skills',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'domains',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'frameworks',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'languages',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('projects', 'match_count')
    op.drop_column('projects', 'updated_at')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index('idx_user_messages', table_name='chat_messages')
    op.drop_index('idx_unread_messages', table_name='chat_messages')
    op.drop_index('idx_conversation', table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_to_user_id'), 'chat_messages', ['to_user_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_project_id'), 'chat_messages', ['project_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_from_user_id'), 'chat_messages', ['from_user_id'], unique=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_messages', 'to_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_messages', 'from_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_messages', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('chat_messages', 'is_read')
    op.drop_index(op.f('ix_candidates_title'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_is_active'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_experience_years'), table_name='candidates')
    op.drop_index('idx_experience_active', table_name='candidates')
    op.alter_column('candidates', 'candidate_vector',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('candidates', 'education',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('candidates', 'certifications',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('candidates', 'skills',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('candidates', 'work_history',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('candidates', 'updated_at')
    # ### end Alembic commands ###
